# GET http://localhost:3000


GET http://localhost:3000/listSchools?latitude=10.55&longitude=77.64


# POST http://localhost:3000/addSchool
# Content-Type: application/json

# {
#   "name": "Periyar school",
#   "address": "Sundar nagar, Trichy",
#   "latitude": 11.0827,
#   "longitude": 82.2707
# }